### ISSUE TITLE
Using useSafeAppsSDK and useSafeBalances with Vue

### ISSUE THREAD

**Issue by kirylknysh** [safe-global/safe-apps-sdk#312]
```
import { useSafeAppsSDK } from '@gnosis.pm/safe-apps-react-sdk';
import { useSafeBalances } from './hooks/useSafeBalances';
```
Can I use that hooks in Vue.js app? I tried some different ways, but always get errors, connected with react or typescript

**Comment by mikheevm** [comment]
As the package name hints, they're react hooks. I don't think you can use them with Vue
