### ISSUE TITLE
When I use safe-app-sdk in Next.js, I have got error "window is not defined."

### ISSUE THREAD

**Issue by climax-solution** [safe-global/safe-apps-sdk#317]
Hello.
I am trying to use "@gnosis.pm/safe-apps-web3-react" in Next.js. But I have got error "window is not defined".
If anyone know how to fix, please help me.
![image](https://user-images.githubusercontent.com/85182580/173168901-2f6f8488-34bc-40e3-90a7-80bdd84374d0.png)

**Comment by yagopv** [comment]
Hi @climax-solution. Is your repo public or can i take a look to the code?

Thanks

**Comment by dasanra** [comment]
Fix is ready, will be delivered in next SDK release
