### ISSUE TITLE
@gnosis.pm/safe-apps-wagmi needs more permissive peer dependency of @wagmi/core 

### ISSUE THREAD

**Issue by matthewlilley** [safe-global/safe-apps-sdk#348]
Currently @gnosis.pm/safe-apps-wagmi is incompatible with latest versions of wagmi due to mismatching of peer dependency @wagmi/core. It should have a more permissive dependency.

**Comment by mikhailxyz** [comment]
we updated the wagmi package to support the lastest versions of wagmi
