### ISSUE TITLE
Unable to set `gasLimit`(`safeTxGas`) through the SDK

### ISSUE THREAD

**Issue by Adamj1232** [safe-global/safe-apps-sdk#379]
I am trying to support a user issue with gnosis where the devs are unable to programitically set the gasLimi prop for a transaction without it being overridden by Safe.
My testing is yielding the same issue. 
Below is my debugging code:
```
    const tx = {
      to: toAddress,
      value: 1000000000000000,
      data: '0x',
    }
    const params = {
      safeTxGas: 500000,
    };
    // wallet.instance is the exposed gnosis safe-apps-sdk instance after initiailization
    let trans = await wallet.instance.txs.send({txs:[tx], params})
    console.log(trans)
```
The transaction is submitted to the Safe through the app.
Same issue happens when the transaction is populated with the gasLimit property, it is overridden and ignored.
Any ideas on what is happening?

Package versions:     
"@gnosis.pm/safe-apps-provider": "^0.14.0",
"@gnosis.pm/safe-apps-sdk": "^7.8.0",

Web3-Onboard githuhb issue for context - https://github.com/blocknative/web3-onboard/issues/1255
![image](https://user-images.githubusercontent.com/24457880/196554932-354823ac-7b46-4c1e-b5bd-6220fa1b3e05.png)

**Comment by mikhailxyz** [comment]
We do not support setting the ethereum transaction's gas limit, the wallet will calculate it for you. You can use the `safeTxGas` property to control the minimum amount of gas that has to be supplied to the Safe transaction
