### ISSUE TITLE
@gnosis.pm/safe-apps-wagmi incompatible with wagmi 0.8

### ISSUE THREAD

**Issue by matthewlilley** [safe-global/safe-apps-sdk#395]
Wagmi 0.8 requires connectors be exported as ESM

**Comment by sarinniural** [comment]
@matthewlilley I just copied the safeconnector code locally to make it work for now

**Comment by mikhailxyz** [comment]
@matthewlilley @sarinniural I can't reproduce this with wagmi 0.8.7 in the example app from the repo. I also don't see how wagmi and ESM would be connected since wagmi is a library and not a build tool. Could you please share a reproduction example or more information like which error you exactly had?

**Comment by sarinniural** [comment]
@mikhailxyz thanks for fixing it, looks like it is working

**Comment by matthewlilley** [comment]
@mikhailxyz there is still come incompatibility problems.

Property 'onAccountsChanged' is protected but type 'SafeConnector' is not a class derived from 'Connector<Provider, Options, Signer>'.

**Comment by mikhailxyz** [comment]
> @mikhailxyz there is still come incompatibility problems.
> 
> Property 'onAccountsChanged' is protected but type 'SafeConnector' is not a class derived from 'Connector<Provider, Options, Signer>'.

Is there an example/code snippet where I can reproduce it? I do not run into this error when using the example app

**Comment by matthewlilley** [comment]
@mikhailxyz this is a typescript error which blocks compilation and can only be ignored by ignoring ts which isn't really a solution. If you enable strict mode you'll see it when trying to add this connector to wagmi client connectors array.

**Comment by sarinniural** [comment]
@matthewlilley I did not have this issue with the recent version of wagmi  0.8.7 and safe-apps-wagmi 1.2.0.

I have ts and strict mode enabled

**Comment by sarinniural** [comment]
@mikhailxyz any ideas on my issue above, my own work to update the versions is pending.

**Comment by mikhailxyz** [comment]
> @mikhailxyz any ideas on my issue above, my own work to update the versions is pending.

could you please do fresh node modules install? we released an update to the transient wagmi wrapper dependency (safe-apps-provider)

**Comment by mikhailxyz** [comment]
@matthewlilley I'm sorry but I can't reproduce it... I can take a look if you give me an example. Also I double checked and the wagmi connector indeed derived from the Connector class:
```
import { Connector, Chain, ConnectorNotFoundError } from '@wagmi/core';

class SafeConnector extends Connector<SafeAppProvider, SafeOpts | undefined> {
```

**Comment by franm91** [comment]
@matthewlilley hello, did you find a solution for the type error? I'm with the same problem when adding the connector to the array

**Comment by matthewlilley** [comment]
> @matthewlilley hello, did you find a solution for the type error? I'm with the same problem when adding the connector to the array

I just owned the code and updated it so it was compatible. I keep nudging wagmi folks to pull this into the core since it's a critical connector for some apps and is annoying when it falls out of sync.

**Comment by mikhailxyz** [comment]
@franm91 @matthewlilley could you please give us a reproducible example of the type error? we're also interested to get this fixed but we cannot reproduce it

**Comment by cruzdanilo** [comment]
@mikhailxyz here is a reproducible example of the error: https://github.com/cruzdanilo/safe-wagmi-bug

i just created a new app with `create-wagmi` and then added the safe connector.
