### ISSUE TITLE
could give a function to get transaction result accurately when ransactions conflict as they use the same nonce

### ISSUE THREAD

**Issue by tercel** [safe-global/safe-apps-sdk#397]
We can not just use getBySafeTxHash to get a nonce task when ransactions conflict as they use the same nonce. Beacuse there are two different safeTxHash match the same none.
We use Safe Transaction Service API to resovle this issue, but this is not good idea here.
So could your give a function to get transaction result accurately, for example getBySafeNonce(safeAddress,  safeNonce) to hanlde this issue.

**Comment by mikhailxyz** [comment]
> We use Safe Transaction Service API to resovle this issue, but this is not good idea here.

Why is it not a good idea? This is the only solution here and even if we'd add this to the sdk, it'd just do this under the hood.

**Comment by dasanra** [comment]
@tercel may I ask which is your use case for needing to get the transaction list from a Safe App context? Usually when integrating as a Safe App the web interface would care about transactions flow.

Maybe for this case would be a better suit the https://github.com/safe-global/safe-core-sdk which is meant for apps that use the Safe contracts or services directly

**Comment by tercel** [comment]
Thanks for you tell me using safe-core-sdk. Sorry, I do not known it existed before.  The safe-core-sdk is more flexible  for developer. 
Go back my question. The root cause is that We can easy to use a function to get a nonce task when ransactions conflict as they use the same nonce. I go through safe-core-sdk/safe-service-client code, but I do not found a function to get a nonce task. So, I suggest that we can add getBySafeNonce(safeAddress, safeNonce) in safe-apps-sdk to use friendly. By the way we can add getTransactionsBySafeNonce(safeAddress, safeNonce) in safe-core-sdk/safe-service-client. If we need to handle it accurately, we need add a filter option "nonce" for  /v1/safes/{address}/all-transactions/.

**Comment by mikhailxyz** [comment]
> Thanks for telling me using safe-core-sdk. Sorry, I do not known it existed before. The safe-core-sdk is more flexible for developer. Go back my question. The root cause is that We can easy to use a function to get a nonce task when ransactions conflict as they use the same nonce. I go through safe-core-sdk/safe-service-client code, but I do not found a function to get a nonce task. So, I suggest that we can add getBySafeNonce(safeAddress, safeNonce) in safe-apps-sdk to use friendly. By the way the getAllTransactions is not support the nonce option in safe-core-sdk/safe-service-client. If we need to handle it accurately, we need add a filter option "nonce" for /v1/safes/{address}/all-transactions/.

Does your Safe App manage conflicting transactions? Why can't you just use the Safe wallet application?

**Comment by tercel** [comment]
> Yes, I use /v1/safes/{address}/all-transactions/ to resolve /v1/safes/{address}/all-transactions/ to get the same safe nonce transactions to handle it.
 Yes, Safe wallet application can handle it. But our app need known a task was done when  conflicting transactions.
Because the first user can get a safe transaction result, we can not use this safeTxHash to known this request was done.
Could you give a good solution. Thanks again for your help.

**Comment by tercel** [comment]
> > Thanks for telling me using safe-core-sdk. Sorry, I do not known it existed before. The safe-core-sdk is more flexible for developer. Go back my question. The root cause is that We can easy to use a function to get a nonce task when ransactions conflict as they use the same nonce. I go through safe-core-sdk/safe-service-client code, but I do not found a function to get a nonce task. So, I suggest that we can add getBySafeNonce(safeAddress, safeNonce) in safe-apps-sdk to use friendly. By the way the getAllTransactions is not support the nonce option in safe-core-sdk/safe-service-client. If we need to handle it accurately, we need add a filter option "nonce" for /v1/safes/{address}/all-transactions/.
> 
> Does your Safe App manage conflicting transactions? Why can't you just use the Safe wallet application?

Yes, I use /v1/safes/{address}/all-transactions/ to resolve /v1/safes/{address}/all-transactions/ to get the same safe nonce transactions to handle it.
 Yes, Safe wallet application can handle it. But our app need known a task was done when  conflicting transactions.
Because the first user can get a safe transaction result, we can not use this safeTxHash to known this request was done.
Could you give a good solution. Thanks again for your help.

**Comment by mikhailxyz** [comment]
> > > Thanks for telling me using safe-core-sdk. Sorry, I do not known it existed before. The safe-core-sdk is more flexible for developer. Go back my question. The root cause is that We can easy to use a function to get a nonce task when ransactions conflict as they use the same nonce. I go through safe-core-sdk/safe-service-client code, but I do not found a function to get a nonce task. So, I suggest that we can add getBySafeNonce(safeAddress, safeNonce) in safe-apps-sdk to use friendly. By the way the getAllTransactions is not support the nonce option in safe-core-sdk/safe-service-client. If we need to handle it accurately, we need add a filter option "nonce" for /v1/safes/{address}/all-transactions/.
> > 
> > 
> > Does your Safe App manage conflicting transactions? Why can't you just use the Safe wallet application?
> 
> Yes, I use /v1/safes/{address}/all-transactions/ to resolve /v1/safes/{address}/all-transactions/ to get the same safe nonce transactions to handle it. Yes, Safe wallet application can handle it. But our app needs to known a task when it's over if conflicting transactions. Because the first user can get a safe transaction result, we can not use this safeTxHash to known this request was done. Could you give a good solution. Thanks again for your help.

You can use `/v1/safes/{address}/multisig-transactions/` endpoint, it takes query parameters for nonce.
