### ISSUE TITLE
Potential Cra-Template Issues

### ISSUE THREAD

**Issue by asharma13524** [safe-global/safe-apps-sdk#400]
I am continuously getting the following below error when running 

```
npx create-react-app drain-safe --template @gnosis.pm/cra-template-safe-app
```

I believe it has to do with the version here https://github.com/safe-global/safe-apps-sdk/blob/master/packages/cra-template-safe-app/template.json#L15.

see https://github.com/testing-library/react-testing-library/issues/1121#issuecomment-1242335979 for example.

Any idea what might be going on here? Thanks.

```
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.0.0" from @testing-library/react@13.4.0
npm ERR! node_modules/@testing-library/react
npm ERR!   dev @testing-library/react@"^13.4.0" from the root project
```

Curious what I may be missing on my end, thanks!

Have attempted to move down to react@17.0.2 and react-dom@17.0.2 to no avail.

----------------------------------------------------

Update: I have gotten the command to not error out. For anyone looking to get this up and running for the time being:

the following fails:
```npx create-react-app drain-safe --template @gnosis.pm/cra-template-safe-app@4.2.0```

and the following works:
1. ```npx create-react-app drain-safe --template @gnosis.pm/cra-template-safe-app@4.1.1```. 
Again, I believe there are some broken fonts in this version but the command does not error out.

2. Remove related font code here https://github.com/safe-global/safe-apps-sdk/pull/388/files#diff-68c12a430f865c61eee3d09fe68f486c048af196cf7a2b347f0c5105c94f01c8L1-L2.

3. ```npm start``` (or yarn)

**Comment by asharma13524** [comment]
thanks

**Comment by mikhailxyz** [comment]
@asharma13524 thanks for a well written report 🙏
