### ISSUE TITLE
[safe-apps-wagmi] Support wagmi 0.8.x

### ISSUE THREAD

**Issue by kasparkallas** [safe-global/safe-apps-sdk#432]
I see the version range is `"@wagmi/core": ">= 0.3.8 < 0.8.0"` (explicitly upper bounded) but `wagmi` has been on `0.8.x` for about a month. A notable change is that it's pure ESM now https://github.com/wagmi-dev/wagmi/pull/1173 so it might not be a trivial change.

Have you guys already looked into this?  I noticed that @mikhailxyz created a branch for 0.8.x but deleted it.

**Comment by cruzdanilo** [comment]
this pr was wrongfully closed: https://github.com/safe-global/safe-apps-sdk/issues/395

**Comment by mwawrusch** [comment]
+1 on this one.

**Comment by mihoward21** [comment]
+ 1 too, would be great to have this supported!

**Comment by bannik** [comment]
I have created this pr to support up to wagmi 10.10: https://github.com/safe-global/safe-apps-sdk/pull/441

I have tested this approach and would be happy to show how exactly I was able to resolve the issue

**Comment by kasparkallas** [comment]
I see that it got updated but it doesn't seem quite right to me. `wagmi` moved to pure ESM modules while this package is still outputting CommonJS format with _require_'s.

https://github.com/wagmi-dev/wagmi/blob/main/packages/core/package.json

**Comment by mikhailxyz** [comment]
@kasparkallas why would wagmi's module system influence the module system we use? I'm not getting it. It's a library not a bundler

**Comment by mikhailxyz** [comment]
`@gnosis.pm/safe-apps-wagmi@2.1.0` now supports wagmi 0.8.x

**Comment by kasparkallas** [comment]
> @kasparkallas why would wagmi's module system influence the module system we use? I'm not getting it. It's a library not a bundler

Good question, I'm not an expert on the matter, I'm trying to figure it out.

I'm using Next.js and running into this on `next build`:
```
Collecting page data .Error [ERR_REQUIRE_ESM]: require() of ES Module /my-dapp/node_modules/@wagmi/core/dist/index.js from /my-dapp/node_modules/@gnosis.pm/safe-apps-wagmi/dist/index.js not supported.
Instead change the require of /my-dapp/node_modules/@wagmi/core/dist/index.js in /my-dapp/node_modules/@gnosis.pm/safe-apps-wagmi/dist/index.js to a dynamic import() which is available in all CommonJS modules.
```

`next build` does pre-rendering while running in Node runtime without any bundling (I think). It gets to `@gnosis.pm/safe-apps-wagmi` which tries to load a ES module with `require`statement. 

But this is what the Node docs state (https://nodejs.org/api/esm.html#interoperability-with-commonjs):
<img width="749" alt="image" src="https://user-images.githubusercontent.com/10894666/216305103-4cbc41f8-f0d3-4181-9785-124f0bd627d8.png">
<img width="747" alt="image" src="https://user-images.githubusercontent.com/10894666/216305314-456326cb-93f5-4fd7-afc2-f8427c85d22f.png">

Messing around with `next.config.js`, trying to transpile `@gnosis.pm/safe-apps-wagmi` and using `experimental.esmExternals: 'loose'`, I run into the same error in another shape:
```
Module not found: ESM packages (@wagmi/core) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals
```

I could probably theoretically work around this by using Next.js' dynamic import for `@gnosis.pm/safe-apps-wagmi` but the problem with this is that `wagmi` & `@rainbow-me/rainbowkit` wrap the whole React component tree and are set up synchronously with the connectors. 

I know this is an annoying matter. Maybe @tmm can give us pointers? :pray:

**Comment by mikhailxyz** [comment]
@kasparkallas thanks for the explanation. good news - Safe connector [will be included](https://github.com/wagmi-dev/references/pull/91) in wagmi's references repo and will be distributed alongside other wagmi connectors

**Comment by kasparkallas** [comment]
Just a small follow-up that using the Safe connector from wagmi's references repo worked without any problems! :pray:
