### ISSUE TITLE
ERR_REQUIRE_ESM with Wagmi

### ISSUE THREAD

**Issue by gmaijoe** [safe-global/safe-apps-sdk#436]
Hi all, getting the following error when importing 

`import { SafeConnector } from '@gnosis.pm/safe-apps-wagmi';` - I am running v1.2.0

Error: require() of ES Module /node_modules/@wagmi/core/dist/index.js from /node_modules/@gnosis.pm/safe-apps-wagmi/dist/index.js not supported.
Instead change the require of /node_modules/@wagmi/core/dist/index.js in /node_modules/@gnosis.pm/safe-apps-wagmi/dist/index.js to a dynamic import() which is available in all CommonJS modules.

Any ideas on how to resolve? thanks in advance

**Comment by cruzdanilo** [comment]
related to #395

**Comment by bannik** [comment]
I have created a pr which resolves this issue: https://github.com/safe-global/safe-apps-sdk/pull/441 feel free to try the solution out locally I would be happy to guide you through.

**Comment by kasparkallas** [comment]
Use this now `import { SafeConnector } from "@wagmi/connectors/safe"; `: https://wagmi.sh/react/connectors/safe

**Comment by dasanra** [comment]
Closing this issue as now the Wagmi connector is available at Wagmi repository.

Find the docs on the comment above
