### ISSUE TITLE
bug: can't use `undefined` value for contract writes

### ISSUE THREAD

**Issue by Max-3-7** [safe-global/safe-apps-sdk#480]
Hey,

I'm having an issue with contract writes that require the value to be `undefined` when connected to a safe. 

For example with viem/wagmi, this throws an error and you can't sign it from your safe:
```
const { config } = usePrepareContractWrite({
    abi: erc20ABI,
    address: token,
    args: amount ? [spender, amount] : undefined,
    chainId,
    functionName: 'approve',
})
```
<img width="780" alt="Screenshot 2023-05-25 at 10 17 00" src="https://github.com/wagmi-dev/viem/assets/52084503/f20e18d6-bcbd-4343-8262-f5458bbda616">

But this works:
```
const { config } = usePrepareContractWrite({
    abi: erc20ABI,
    address: token,
    args: amount ? [spender, amount] : undefined,
    chainId,
    functionName: 'approve',
    value: BigInt(0) as any // workaround for safe app
})
```

The SDK could accept the value `undefined` and convert it to 0 instead of throwing an error?

------

https://github.com/wagmi-dev/viem/issues/579

**Comment by mmv08** [comment]
I'm sorry, but I don't get how it's an issue. The ABI expects an address and a number, and it errors when you pass undefined - it seems like an expected behaviour to me.

> The SDK could accept the value undefined and convert it to 0 instead of throwing an error?

You could do it explicitly on the client side. IMO it's not good to include such implicit behaviour.

**Comment by Max-3-7** [comment]
The ABI doesn't expect a value

**Comment by mmv08** [comment]
Ahh, apologies. I misread the issue. Agree this should be investigated.

**Comment by Max-3-7** [comment]
No worries! Thanks for the quick reply.

We noticed the issue when migrating from ethers to viem, so I assume ethers was handling this differently than viem.

**Comment by Anup9444** [comment]
did you guys find the solution for this problem 
I am also getting the same error
