### ISSUE TITLE
Add MilkmApp to Safe Store

### ISSUE THREAD

**Issue by yvesfracari** [safe-global/safe-apps-sdk#554]
As part of a [grant](https://forum.cow.fi/t/grant-application-safe-app-for-creating-milkman-orders/1920) with CoW Protocol, [bleu](https://github.com/bleu-fi) developed a Safe App to create Milkman Orders. The app was sent to Safe Review following this [guide](https://docs.safe.global/apps-sdk-release), and I received the information that it is ready to be listed in the Store. I was also informed that the next step is to open this PR.

The app link is: [https://cow-tools-bleu-fi.vercel.app](https://cow-tools-bleu-fi.vercel.app)

Let me know if you guys need more information or if I need to do something else.

**Comment by dasanra** [comment]
Hey, this is not the repo for the apps submission. 

Please follow[ this guide for the process](https://github.com/5afe/safe-apps-list/blob/main/README.md)
