### ISSUE TITLE
Add Opus ETH Staking App by Chorus One to Safe Store

### ISSUE THREAD

**Issue by RishiSid** [safe-global/safe-apps-sdk#557]
# Description
---
name: List Opus ETH Staking App request
about: Add a Safe app
---

## Type
- New addition

## Revision checks
 - [x] Used smart contracts were audited.
 - [x]  Your Safe App include a manifest.json file at the root [with the required data](https://docs.safe.global/safe-core-aa-sdk/safe-apps/release).
  - [x] The app can be loaded as a custom Safe App in the Apps section of https://app.safe.global/.
 - [x]  The app auto-connects to the Safe.
  - [x] You are able to trigger and execute one transaction with a Safe.
  - [x] RPC requests are optimized (not triggering many requests in a very short time period).

## Name/Description
Name: ETH Staking by Chorus One
Description: Stake ETH with Chorus One's MEV Max Pool and earn maximum MEV rewards with enterprise-grade security. Get 100% slashing protection with full custody of your assets.

## Compatible Networks
- Mainnet

## Code for review
- Code is closed-sourced. We can grant access to devs for review if needed

## Audit document
We're using the following smart contracts [Stakewise Smart Contracts](https://github.com/stakewise/v3-core/tree/main/contracts) under the hood which have been audited.
|Contracts| Contract Code URL| Audit Report |
|-|-|-|
|Stakewise smart contracts| https://github.com/stakewise/v3-core/tree/main/contracts|https://github.com/stakewise/v3-core/tree/main/audits|
|Eigenlayer smart contracts| https://github.com/Layr-Labs/eigenlayer-contracts|https://docs.eigenlayer.xyz/eigenlayer/security/audits|

### App URL
- Link to app: https://opus.chorus.one/pool/stake
- Link to company website: https://chorus.one/

## Team information
- Project logo: https://opus.chorus.one/portal/_next/static/media/opus_logo.73ea0090.svg
- Project landing page: https://opus.chorus.one/pool/stake
- Team or discord contact: https://discord.gg/bQ6JWVa
- Twitter link: https://twitter.com/ChorusOne 
- Github link: https://github.com/ChorusOne

**Comment by dasanra** [comment]
Hey, this is not the repo for the apps submission. 

Please follow[ this guide for the process](https://github.com/5afe/safe-apps-list/blob/main/README.md)
