### ISSUE TITLE
Can not add localhost as custom Safe App anymore.

### ISSUE THREAD

**Issue by einaralex** [safe-global/safe-apps-sdk#558]
While testing out my Safe App, I used to be able to add localhost as a custom app. Now I get an error "The app doesn't support Safe App functionality."

I've recently changed browsers, so I re-visited Chrome and found that my localhost custom app is still cached there and still works there. But if I open up an incognito window and try to add it, I also get "The app doesn't support Safe App functionality."

Dev console says `The FetchEvent for "http://localhost:3000/manifest.json" resulted in a network error response: the promise was resolved with an error response object.`, but it's there if I visit the url and it's the same manifest.json we use for our production app.

**Comment by dasanra** [comment]
Could you confirm that you configured CORS correctly for the app? For me it's possible to access an app via localhost
https://github.com/safe-global/safe-apps-sdk/tree/main/packages/safe-apps-sdk#cors
