### ISSUE TITLE
Version mismatch between `version.ts` and `package.json` in safe-apps-sdk

### ISSUE THREAD

**Issue by olegshilov** [safe-global/safe-apps-sdk#604]
There is a version mismatch in the safe-apps-sdk package. The version.ts file defines the SDK version as 9.0.0, while package.json lists it as 9.1.0. This inconsistency can lead to confusion regarding the correct SDK version.

Link to the files:
[version.ts](https://github.com/safe-global/safe-apps-sdk/blob/main/packages/safe-apps-sdk/src/version.ts#L1)
[package.json](https://github.com/safe-global/safe-apps-sdk/blob/main/packages/safe-apps-sdk/package.json#L3)

**Comment by dasanra** [comment]
Thank you for your report.

Solved by #608
